{
 "title": "IntDB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "启动时间",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "intdb_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "健康度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "intdb_api_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "活跃流数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "intdb_flows_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "内存占用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "intdb_memory_usage_estimate_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}